name: Fetch Wikipedia Top

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日12:00(JST)に実行
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run script
        run: python trend.py
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add trend.csv
          git commit -m "update: daily trend" || echo "no changes"
          git push
